### Add to Cart
POST http://localhost:3000/cart/377765fc-413b-4e23-8168-b7e71fc129cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOTUxMTJhNi0zN2QzLTQzMDUtODY2Ni01NDE2NjllMDkzODIiLCJlbWFpbCI6ImR1bmNhbm95dWdpMjAwMUBnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTA0MTA0OTUsImV4cCI6MTc1MTI3NDQ5NX0.XQbS8zwZErJEhil7wrZFNwcmo8Ed51eV9DtGD9GtpS4
Content-Type: application/json

{
  "quantity": 10
}

### Get Cart Items
GET http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOTUxMTJhNi0zN2QzLTQzMDUtODY2Ni01NDE2NjllMDkzODIiLCJlbWFpbCI6ImR1bmNhbm95dWdpMjAwMUBnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTA0MTA0OTUsImV4cCI6MTc1MTI3NDQ5NX0.XQbS8zwZErJEhil7wrZFNwcmo8Ed51eV9DtGD9GtpS4
### Update Cart Item Quantity
PATCH http://localhost:3000/cart/377765fc-413b-4e23-8168-b7e71fc129cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOTUxMTJhNi0zN2QzLTQzMDUtODY2Ni01NDE2NjllMDkzODIiLCJlbWFpbCI6ImR1bmNhbm95dWdpMjAwMUBnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTA0MTA0OTUsImV4cCI6MTc1MTI3NDQ5NX0.XQbS8zwZErJEhil7wrZFNwcmo8Ed51eV9DtGD9GtpS4
Content-Type: application/json

{
  "quantity": 5
}

### Remove an item from Cart
DELETE http://localhost:3000/cart/377765fc-413b-4e23-8168-b7e71fc129cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOTUxMTJhNi0zN2QzLTQzMDUtODY2Ni01NDE2NjllMDkzODIiLCJlbWFpbCI6ImR1bmNhbm95dWdpMjAwMUBnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTA0MTA0OTUsImV4cCI6MTc1MTI3NDQ5NX0.XQbS8zwZErJEhil7wrZFNwcmo8Ed51eV9DtGD9GtpS4

### Clear entire Cart
DELETE http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOTUxMTJhNi0zN2QzLTQzMDUtODY2Ni01NDE2NjllMDkzODIiLCJlbWFpbCI6ImR1bmNhbm95dWdpMjAwMUBnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTA0MTA0OTUsImV4cCI6MTc1MTI3NDQ5NX0.XQbS8zwZErJEhil7wrZFNwcmo8Ed51eV9DtGD9GtpS4
