### Register Customer
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "fullName": "Eddy",
  "email": "eddymax3715@gmail.com",
  "password": "123456789",
  "phoneNumber": "0710592567",
  "address": "Nairobi, Kenya"
}
