### Register Customer
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "fullName": "Harrison",
  "email": "safenot094@gmail.com",
  "password": "123456",
  "phoneNumber": "0711592567",
  "address": "Nairobi, Kenya"
}
