### Reset password using token
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "token": "9c415c3241e7a54cd6d9fe3bc1bd2bfe2907cf7635bf6e6f3c6f26e5de620727",
  "newPassword": "dante@7827",
  "confirmPassword": "dante@7827"
}
