### Reset password using token
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "token": "7d27fa50dcf8c299e1a74228d91dbf5d4ab4a63a4d698688447ad26579fb4b74",
  "newPassword": "12345678",
  "confirmPassword": "12345678"
}
